title = "Code and stuff"
baseURL = "https://www.drzon.net/"
languageCode = "en-us"
Copyright = "All rights reserved - 2017"
canonifyurls = true
DisqusShortname = "drzone"

[params]
  # description = "this is my description"
  cover = "images/cover.jpg"
  author = "Michael DeRazon"
  authorlocation = "New York, USA"
  authorwebsite = "https://www.drzon.net"
  # bio= "my bio"
  logo = "images/selfie.png"
  googleAnalyticsUserID = "UA-44481923-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "mderazon"
  twitterName = "mderazon"
  # facebookName = ""
  linkedinName = "mderazon"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
